apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-pipeline
  namespace: hsaid-jenkins

spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/hsaid4327/pipeline-webhook-test.git
    sourceSecret:
      name: gits-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []
